### ISSUE TITLE
Inconsistencies between `nhmmer` and `pyhmmer.nhmmer`

### ISSUE THREAD

**Issue by althonos** [moshi4/pybarrnap#2]
Hi @moshi4, glad to see PyHMMER is useful :smiley: 

Regarding the following on the `README`:

> pybarrnap is developed experimentally. I have confirmed that it gives almost the same results as barrnap, but the evalue is slightly different. Maybe there is a slight difference in behavior between `nhmmer` and `pyhmmer.nhmmer` when setting the window_length option?

Do you have an example sequence where this happens? I'd be happy to investigate and to fix it if that indeed a PyHMMER bug.

**Comment by moshi4** [comment]
Hi @althonos, thanks for your comment.

In nhmmer, there is a difference in E-value depending on whether `--w_length` is set or not. On the other hand, pyhmmer.nhmmer does not have any difference in E-value depending on the `window_length` setting of the Builder class.

The following is the data to reproduce the result of nhmmer and pyhmmer.nhmmer.

[nhmmer_vs_pyhmmer.nhmmer_diff.zip](https://github.com/moshi4/pybarrnap/files/14473566/nhmmer_vs_pyhmmer.nhmmer_diff.zip)

`bash nhmmer_example.sh` and `python pyhmmer.nhmmer_example.py` commands output the results with and without window_length setting, respectively.

**Comment by althonos** [comment]
So at the moment the `window_length` option was only used in the builder to build new HMMs, so it was completely ignored when `nhmmer` was called with pre-built HMMs. I'll work on a patch but that needs a bit of refactoring.

**Comment by moshi4** [comment]
I am closing this issue as I have released v0.2.0 which fixes the problem. Thanks for your great contribution :smiley:

**Comment by althonos** [comment]
Thanks!
